Feature/update readme
ga4gh/ga4gh-starter-kit-passport-broker pull request #16
Opened 2022-07-20 19:21 UTC by emre-f

2022-07-20 19:32 UTC, yash-puligundla requested changes
Hi Emre,

Looks good. Just some feedback related to the structure. 
1. Having a separate CONFIGURATION.md will make it uniform to other starter kits READMEs.
2. Consider adding a different table for each of the top-level Keys that talks about each of the attributes & their default values. I would follow the data-connect CONFIGURATION.md example, while making sure all the fields related to passport broker are added. 
3. I would remove the link to the example config file, as the contents are already displayed. Also, this way we will not have a dependency on a test file resource.

2022-07-21 18:53 UTC, yash-puligundla commented on CONFIGURATION.md
> +The Passport Broker service can be configured with custom properties, affecting behavior at runtime. There is an example config file present in this repo:
```suggestion
The Passport Broker service can be configured with custom properties, affecting behavior at runtime. Here is an example config file:
```

2022-07-21 19:06 UTC, yash-puligundla commented
Hi @emre-f  I have added a few suggestions as in-line comments. Let me know if you have any questions

2022-07-21 20:36 UTC, emre-f commented
@yash-puligundla are you talking about the 3 points you had above? I completed my changes regarding those points. What do you mean by "in-line comments? I couldn't see anything else.

2022-07-21 21:30 UTC, yash-puligundla commented on CONFIGURATION.md
> +The Passport Broker service can be configured with custom properties, affecting behavior at runtime. There is an example config file present in this repo:
```suggestion
The Passport Broker service can be configured with custom properties, affecting behavior at runtime. Here is an example config file:
```

2022-07-21 21:30 UTC, yash-puligundla commented on CONFIGURATION.md
> +The YAML config file must contain a single root property of `drs`, under which all subconfigurations are located:
```suggestion
The YAML config file must contain a single root property of `passportBrokerConfig`, under which all subconfigurations are located:
```

2022-07-21 21:30 UTC, yash-puligundla commented on CONFIGURATION.md
> +| brokerSecret | ? | insecureSecretPleaseOverride |
```suggestion
| brokerSecret | The secret string used by the passport broker to mint a Passport JWT | insecureSecretPleaseOverride |
```

2022-07-21 21:32 UTC, yash-puligundla commented
Sorry @emre-f, I forgot to submit the comments. you should be able to see them now.

2022-07-22 14:24 UTC, emre-f commented
@yash-puligundla added the changes you have suggested, they all looked correct to me.

2022-07-22 14:29 UTC, yash-puligundla approved these changes
Looks good, Thanks Emre. Approving & merging the PR.

2022-07-22 14:30 UTC, merged